# This is a basic workflow to help you get started with Actions

name: checkpatch

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, reopened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkpatch:
    uses: zhn-test/public-actions/.github/workflows/checkpatch.yml@main
    secrets: inherit
